# Generated by Django 3.0.3 on 2020-06-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_grade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
