# Generated by Django 3.0.3 on 2020-06-07 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20200607_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_grade',
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Student')),
            ],
        ),
    ]
