# Generated by Django 3.0.3 on 2020-07-11 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20200610_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher_name',
            new_name='name',
        ),
    ]
